-- "products" tablosunu oluştur
CREATE TABLE IF NOT EXISTS public.products (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  description text NOT NULL,
  stock integer NOT NULL DEFAULT 0,
  price numeric NOT NULL DEFAULT 0,
  image_url text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- RLS (Row Level Security) ayarları
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

-- Okuma politikası (Herkes görebilir - Ana sayfa için gerekli)
CREATE POLICY "Products are viewable by everyone" ON public.products
  FOR SELECT USING (true);

-- Ekleme, Güncelleme ve Silme politikaları (Sadece yetkili/giriş yapmış kullanıcılar yapabilir)
CREATE POLICY "Products are insertable by authenticated users only" ON public.products
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Products are updatable by authenticated users only" ON public.products
  FOR UPDATE USING (auth.role() = 'authenticated');

CREATE POLICY "Products are deletable by authenticated users only" ON public.products
  FOR DELETE USING (auth.role() = 'authenticated');
